
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[XPAR_XIIC_NUM_INSTANCES] =
{
	{
		XPAR_MICROBLAZE_0_AXI_IIC_0_DEVICE_ID,
		XPAR_MICROBLAZE_0_AXI_IIC_0_BASEADDR,
		XPAR_MICROBLAZE_0_AXI_IIC_0_TEN_BIT_ADR,
		XPAR_MICROBLAZE_0_AXI_IIC_0_GPO_WIDTH
	},
	{
		XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_DEVICE_ID,
		XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_BASEADDR,
		XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_TEN_BIT_ADR,
		XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_GPO_WIDTH
	}
};


