#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/******************************************************************/


/* Peripheral Definitions for peripheral ATPG */
#define XPAR_ATPG_BASEADDR 0x44A10000
#define XPAR_ATPG_HIGHADDR 0x44A1FFFF


/******************************************************************/


/* Canonical Definitions for peripheral ATPG */
#define XPAR_AUDIO_TPG_0_BASEADDR 0x44A10000
#define XPAR_AUDIO_TPG_0_HIGHADDR 0x44A1FFFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 4

/* Definitions for peripheral MICROBLAZE_0_AXI_GPIO_0 */
#define XPAR_MICROBLAZE_0_AXI_GPIO_0_BASEADDR 0x40010000
#define XPAR_MICROBLAZE_0_AXI_GPIO_0_HIGHADDR 0x40010FFF
#define XPAR_MICROBLAZE_0_AXI_GPIO_0_DEVICE_ID 0
#define XPAR_MICROBLAZE_0_AXI_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_MICROBLAZE_0_AXI_GPIO_0_IS_DUAL 0


/* Definitions for peripheral MICROBLAZE_0_AXI_GPIO_1 */
#define XPAR_MICROBLAZE_0_AXI_GPIO_1_BASEADDR 0x40020000
#define XPAR_MICROBLAZE_0_AXI_GPIO_1_HIGHADDR 0x40020FFF
#define XPAR_MICROBLAZE_0_AXI_GPIO_1_DEVICE_ID 1
#define XPAR_MICROBLAZE_0_AXI_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_MICROBLAZE_0_AXI_GPIO_1_IS_DUAL 0


/* Definitions for peripheral MICROBLAZE_0_AXI_GPIO_2 */
#define XPAR_MICROBLAZE_0_AXI_GPIO_2_BASEADDR 0x00025000
#define XPAR_MICROBLAZE_0_AXI_GPIO_2_HIGHADDR 0x00025FFF
#define XPAR_MICROBLAZE_0_AXI_GPIO_2_DEVICE_ID 2
#define XPAR_MICROBLAZE_0_AXI_GPIO_2_INTERRUPT_PRESENT 0
#define XPAR_MICROBLAZE_0_AXI_GPIO_2_IS_DUAL 0


/* Definitions for peripheral MICROBLAZE_0_FZETTON_FMC_GPIO */
#define XPAR_MICROBLAZE_0_FZETTON_FMC_GPIO_BASEADDR 0x00027000
#define XPAR_MICROBLAZE_0_FZETTON_FMC_GPIO_HIGHADDR 0x00027FFF
#define XPAR_MICROBLAZE_0_FZETTON_FMC_GPIO_DEVICE_ID 3
#define XPAR_MICROBLAZE_0_FZETTON_FMC_GPIO_INTERRUPT_PRESENT 0
#define XPAR_MICROBLAZE_0_FZETTON_FMC_GPIO_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_GPIO_0 */
#define XPAR_GPIO_0_BASEADDR 0x40010000
#define XPAR_GPIO_0_HIGHADDR 0x40010FFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_MICROBLAZE_0_AXI_GPIO_0_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_GPIO_1 */
#define XPAR_GPIO_1_BASEADDR 0x40020000
#define XPAR_GPIO_1_HIGHADDR 0x40020FFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_MICROBLAZE_0_AXI_GPIO_1_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_GPIO_2 */
#define XPAR_GPIO_2_BASEADDR 0x00025000
#define XPAR_GPIO_2_HIGHADDR 0x00025FFF
#define XPAR_GPIO_2_DEVICE_ID XPAR_MICROBLAZE_0_AXI_GPIO_2_DEVICE_ID
#define XPAR_GPIO_2_INTERRUPT_PRESENT 0
#define XPAR_GPIO_2_IS_DUAL 0

/* Canonical definitions for peripheral MICROBLAZE_0_FZETTON_FMC_GPIO */
#define XPAR_GPIO_3_BASEADDR 0x00027000
#define XPAR_GPIO_3_HIGHADDR 0x00027FFF
#define XPAR_GPIO_3_DEVICE_ID XPAR_MICROBLAZE_0_FZETTON_FMC_GPIO_DEVICE_ID
#define XPAR_GPIO_3_INTERRUPT_PRESENT 0
#define XPAR_GPIO_3_IS_DUAL 0


/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 2

/* Definitions for peripheral MICROBLAZE_0_AXI_IIC_0 */
#define XPAR_MICROBLAZE_0_AXI_IIC_0_DEVICE_ID 0
#define XPAR_MICROBLAZE_0_AXI_IIC_0_BASEADDR 0x00026000
#define XPAR_MICROBLAZE_0_AXI_IIC_0_HIGHADDR 0x00026FFF
#define XPAR_MICROBLAZE_0_AXI_IIC_0_TEN_BIT_ADR 0
#define XPAR_MICROBLAZE_0_AXI_IIC_0_GPO_WIDTH 1


/* Definitions for peripheral MICROBLAZE_0_FZETTON_FMC_IIC_CTRL */
#define XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_DEVICE_ID 1
#define XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_BASEADDR 0x00028000
#define XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_HIGHADDR 0x00028FFF
#define XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_TEN_BIT_ADR 0
#define XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_GPO_WIDTH 1


/******************************************************************/

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_IIC_0 */
#define XPAR_IIC_0_DEVICE_ID XPAR_MICROBLAZE_0_AXI_IIC_0_DEVICE_ID
#define XPAR_IIC_0_BASEADDR 0x00026000
#define XPAR_IIC_0_HIGHADDR 0x00026FFF
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 1

/* Canonical definitions for peripheral MICROBLAZE_0_FZETTON_FMC_IIC_CTRL */
#define XPAR_IIC_1_DEVICE_ID XPAR_MICROBLAZE_0_FZETTON_FMC_IIC_CTRL_DEVICE_ID
#define XPAR_IIC_1_BASEADDR 0x40800000
#define XPAR_IIC_1_HIGHADDR 0x40800FFF
#define XPAR_IIC_1_TEN_BIT_ADR 0
#define XPAR_IIC_1_GPO_WIDTH 1


/* Definitions for driver SPI */

/* Definitions for driver SPI */
#define XPAR_XSPI_NUM_INSTANCES 1U

/* Definitions for peripheral MICROBLAZE_0_FZETTON_FMC_SPI_CTRL */
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_DEVICE_ID 0U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_BASEADDR 0x00029000U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_HIGHADDR 0x00029FFFU
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_FIFO_EXIST 0U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_FIFO_DEPTH 0U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_SPI_SLAVE_ONLY 0U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_NUM_SS_BITS 3U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_NUM_TRANSFER_BITS 16U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_SPI_MODE 0U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_AXI4_BASEADDR 0U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_AXI4_HIGHADDR 0U
#define XPAR_MICROBLAZE_0_FZETTON_FMC_SPI_CTRL_XIP_MODE 0U

/* Canonical definitions for peripheral MICROBLAZE_0_FZETTON_FMC_SPI_CTRL */
#define XPAR_SPI_0_DEVICE_ID 0U
#define XPAR_SPI_0_BASEADDR 0x00029000U
#define XPAR_SPI_0_HIGHADDR 0x00029FFFU
#define XPAR_SPI_0_FIFO_EXIST 0U
#define XPAR_SPI_0_FIFO_DEPTH 0U
#define XPAR_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_0_NUM_SS_BITS 3U
#define XPAR_SPI_0_NUM_TRANSFER_BITS 16U
#define XPAR_SPI_0_SPI_MODE 0U
#define XPAR_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_SPI_0_AXI4_BASEADDR 0U
#define XPAR_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_SPI_0_XIP_MODE 0U
#define XPAR_SPI_0_USE_STARTUP 0U



/*******************************************************************************************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1U

/* Definitions for peripheral MICROBLAZE_0_UART */
#define XPAR_MICROBLAZE_0_UART_DEVICE_ID 0U
#define XPAR_MICROBLAZE_0_UART_BASEADDR 0x0002A000U
#define XPAR_MICROBLAZE_0_UART_HIGHADDR 0x0002AFFFU
#define XPAR_MICROBLAZE_0_UART_BAUDRATE 115200U
#define XPAR_MICROBLAZE_0_UART_USE_PARITY 0U
#define XPAR_MICROBLAZE_0_UART_ODD_PARITY 0U
#define XPAR_MICROBLAZE_0_UART_DATA_BITS 8U

/* Canonical definitions for peripheral MICROBLAZE_0_UART */
#define XPAR_UARTLITE_0_DEVICE_ID 0U
#define XPAR_UARTLITE_0_BASEADDR 0x0002A000U
#define XPAR_UARTLITE_0_HIGHADDR 0x0002AFFFU
#define XPAR_UARTLITE_0_BAUDRATE 115200U
#define XPAR_UARTLITE_0_USE_PARITY 0U
#define XPAR_UARTLITE_0_ODD_PARITY 0U
#define XPAR_UARTLITE_0_DATA_BITS 8U



#define RX_SS0_BASEADDR			0x0002B000
#define RX_SS1_BASEADDR			0x0002C000
#define RX_SS2_BASEADDR			0x0002D000
#define RX_SS3_BASEADDR			0x0002E000

#define TX_SS0_BASEADDR			0x00040000
#define TX_SS1_BASEADDR			0x00060000
#define TX_SS2_BASEADDR			0x00080000
#define TX_SS3_BASEADDR			0x000A0000


#define DMA_TO_YUV422_0			0x00024000
#define YUV422_TO_DMA_0			0X00020000
#define YUV422_TO_DMA_1			0X00021000
#define YUV422_TO_DMA_2			0X00022000
#define YUV422_TO_DMA_3			0X00023000


#endif

